/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bibloteca.vista;

import com.bibloteca.controlador.BibliotecaController;
import com.bibloteca.controlador.BiblotecaControllerAdmin;
import com.bibloteca.controlador.ControlUsuarioInicio;
import com.bibloteca.modelo.Usuario;
import java.awt.Color;

/**
 *
 * @author r3sn0
 */
public class BiblotecaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Bibloteca
     */
    public BiblotecaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        tipoLibroCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        atributos = new javax.swing.JComboBox<>();
        btnRentar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnPrincipal = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JLabel();
        btnBibloteca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscador.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscador.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtBuscador.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 190, 50));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bibloteca/imagenes/search_8094123 (2).png"))); // NOI18N
        btnBuscar.setBorder(null);
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 70, 50));

        tipoLibroCombo.setBackground(new java.awt.Color(255, 255, 255));
        tipoLibroCombo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tipoLibroCombo.setForeground(new java.awt.Color(0, 0, 0));
        tipoLibroCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libros", "Comics", "Mangas", "Novelas" }));
        jPanel1.add(tipoLibroCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 130, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 610, -1));

        atributos.setBackground(new java.awt.Color(255, 255, 255));
        atributos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        atributos.setForeground(new java.awt.Color(0, 0, 0));
        atributos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Titulo", "Autor", "Genero", "Año de Publicacion", "Ilustrador", "Editorial", "Volumen", "Idioma Original", "Tipo de Narrativa" }));
        jPanel1.add(atributos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 130, -1));

        btnRentar.setText("Rentar");
        jPanel1.add(btnRentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 80, 40));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        btnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        btnPrincipal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrincipal.setText("Principal");
        btnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrincipalMousePressed(evt);
            }
        });

        btnPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPerfil.setText("Administracion");
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerfilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPerfilMousePressed(evt);
            }
        });

        btnBibloteca.setBackground(new java.awt.Color(255, 255, 255));
        btnBibloteca.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBibloteca.setForeground(new java.awt.Color(255, 255, 255));
        btnBibloteca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBibloteca.setText("Bibloteca virtual");
        btnBibloteca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBibloteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBiblotecaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBiblotecaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBiblotecaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btnBibloteca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addComponent(btnBibloteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void btnPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseEntered
        //btnPrincipal.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPrincipalMouseEntered

    private void btnPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseExited
        // btnPrincipal.setForeground(Color.black);
    }//GEN-LAST:event_btnPrincipalMouseExited

    private void btnPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMousePressed
        if(ControlUsuarioInicio.getUsuarioActual().getTipoUsuario().equals("USUARIO")) {
            InicioUsuario vista = new InicioUsuario();
            vista.setVisible(true);
            this.dispose();
        }else if(ControlUsuarioInicio.getUsuarioActual().getTipoUsuario().equals("ADMIN")) {
            InicioUsuarioAdmin vista = new InicioUsuarioAdmin();
            vista.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPrincipalMousePressed

    private void btnPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseEntered
        btnPerfil.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPerfilMouseEntered

    private void btnPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseExited
        btnPerfil.setForeground(Color.black);
    }//GEN-LAST:event_btnPerfilMouseExited

    private void btnPerfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMousePressed
        Perfil vista = new Perfil();
        vista.lblApodo.setText(ControlUsuarioInicio.getUsuarioActual().getApodo());
        vista.lblGamil.setText(ControlUsuarioInicio.getUsuarioActual().getGmail());
        vista.lblNombre.setText(ControlUsuarioInicio.getUsuarioActual().getNombre());
        vista.lblPass.setText(ControlUsuarioInicio.getUsuarioActual().getContraseña());
        vista.lblTelefono.setText(ControlUsuarioInicio.getUsuarioActual().getTelefono());
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerfilMousePressed

    private void btnBiblotecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBiblotecaMouseEntered
        btnBibloteca.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBiblotecaMouseEntered

    private void btnBiblotecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBiblotecaMouseExited
        btnBibloteca.setForeground(Color.black);
    }//GEN-LAST:event_btnBiblotecaMouseExited

    private void btnBiblotecaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBiblotecaMousePressed
        if(ControlUsuarioInicio.getUsuarioActual().getTipoUsuario().equals("USUARIO")) {
            Bibloteca vista = new Bibloteca();
            BibliotecaController control = new BibliotecaController(vista);
            vista.setVisible(true);
            this.dispose();
        }else if(ControlUsuarioInicio.getUsuarioActual().getTipoUsuario().equals("ADMIN")) {
            BiblotecaAdmin vista = new BiblotecaAdmin();
            BiblotecaControllerAdmin control = new BiblotecaControllerAdmin(vista);
            vista.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnBiblotecaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiblotecaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiblotecaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiblotecaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiblotecaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiblotecaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Table;
    public javax.swing.JComboBox<String> atributos;
    private javax.swing.JLabel btnBibloteca;
    public javax.swing.JButton btnBuscar;
    private javax.swing.JLabel btnPerfil;
    private javax.swing.JLabel btnPrincipal;
    public javax.swing.JButton btnRentar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> tipoLibroCombo;
    public javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
