/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bibloteca.vista;

import com.bibloteca.controlador.*;
import com.bibloteca.controlador.ControlUsuarioInicio;
import java.awt.Color;

/**
 *
 * @author r3sn0
 */
public class InicioUsuarioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InicioUsuario
     */
    public InicioUsuarioAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnPrincipal = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JLabel();
        btnBibloteca = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnExplorar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        bg.setBackground(new java.awt.Color(207, 212, 208));
        bg.setMaximumSize(new java.awt.Dimension(900, 500));
        bg.setMinimumSize(new java.awt.Dimension(900, 500));
        bg.setPreferredSize(new java.awt.Dimension(900, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 900, 20));

        jPanel2.setBackground(new java.awt.Color(207, 212, 208));

        btnPrincipal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        btnPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrincipal.setText("Principal");
        btnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrincipalMousePressed(evt);
            }
        });

        btnPerfil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(51, 51, 51));
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPerfil.setText("Administrar");
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerfilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPerfilMousePressed(evt);
            }
        });

        btnBibloteca.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBibloteca.setForeground(new java.awt.Color(51, 51, 51));
        btnBibloteca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBibloteca.setText("Bibloteca virtual");
        btnBibloteca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBibloteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBiblotecaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBiblotecaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBiblotecaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btnBibloteca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addComponent(btnBibloteca, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
            .addComponent(btnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("es poder\"");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 70, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("\"El conocimiento");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 120, 60));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Virtual ");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 130, 30));

        btnExplorar.setBackground(new java.awt.Color(0, 153, 153));
        btnExplorar.setForeground(new java.awt.Color(255, 255, 255));
        btnExplorar.setText("Explorar");
        btnExplorar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnExplorar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExplorar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExplorarMousePressed(evt);
            }
        });
        bg.add(btnExplorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 120, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Library");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 130, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bibloteca/imagenes/fondo.jpg"))); // NOI18N
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 461));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseEntered
        //btnPrincipal.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_btnPrincipalMouseEntered

    private void btnBiblotecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBiblotecaMouseEntered
        btnBibloteca.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBiblotecaMouseEntered

    private void btnPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseEntered
        btnPerfil.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPerfilMouseEntered

    private void btnPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseExited
       // btnPrincipal.setForeground(Color.black);
    }//GEN-LAST:event_btnPrincipalMouseExited

    private void btnBiblotecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBiblotecaMouseExited
        btnBibloteca.setForeground(Color.black);
    }//GEN-LAST:event_btnBiblotecaMouseExited

    private void btnPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseExited
        btnPerfil.setForeground(Color.black);
    }//GEN-LAST:event_btnPerfilMouseExited

    private void btnExplorarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExplorarMousePressed
        if(ControlUsuarioInicio.getUsuarioActual().getTipoUsuario().equals("USUARIO")) {
           Bibloteca vista = new Bibloteca();
           vista.setVisible(true);
           this.dispose();
        }else if(ControlUsuarioInicio.getUsuarioActual().getTipoUsuario().equals("ADMIN")) {
           BiblotecaAdmin vista = new BiblotecaAdmin();
           vista.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_btnExplorarMousePressed

    private void btnPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMousePressed
        if(ControlUsuarioInicio.getUsuarioActual().getTipoUsuario().equals("USUARIO")) {
           InicioUsuario vista = new InicioUsuario();
           vista.setVisible(true);
           this.dispose();
          
        }else if(ControlUsuarioInicio.getUsuarioActual().getTipoUsuario().equals("ADMIN")) {
           InicioUsuarioAdmin vista = new InicioUsuarioAdmin();
           vista.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_btnPrincipalMousePressed

    private void btnBiblotecaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBiblotecaMousePressed
       if(ControlUsuarioInicio.getUsuarioActual().getTipoUsuario().equals("USUARIO")) {
           Bibloteca vista = new Bibloteca();
           BibliotecaController control = new BibliotecaController(vista);
           vista.setVisible(true);
           this.dispose();
        }else if(ControlUsuarioInicio.getUsuarioActual().getTipoUsuario().equals("ADMIN")) {
           BiblotecaAdmin vista = new BiblotecaAdmin();
           BiblotecaControllerAdmin control = new BiblotecaControllerAdmin(vista);
           vista.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_btnBiblotecaMousePressed

    private void btnPerfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMousePressed
       
       
    }//GEN-LAST:event_btnPerfilMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioUsuarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioUsuarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioUsuarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioUsuarioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioUsuarioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnBibloteca;
    private javax.swing.JButton btnExplorar;
    private javax.swing.JLabel btnPerfil;
    private javax.swing.JLabel btnPrincipal;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
