/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bibloteca.vista;

import com.bibloteca.controlador.ControlUsuario;
import com.bibloteca.controlador.UsuarioDAO;
import com.bibloteca.modelo.Usuario;
import java.awt.Color;

/**
 *
 * @author r3sn0
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        iconoVL = new javax.swing.JLabel();
        fondo_Imagen = new javax.swing.JPanel();
        bgLogin = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        lblIniciarSesion = new javax.swing.JLabel();
        lblNombreUsu = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        btnNoTengoCuanta = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        bntIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));

        bg.setBackground(new java.awt.Color(236, 240, 241));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoVL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoVL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bibloteca/imagenes/logo_main (3).png"))); // NOI18N
        bg.add(iconoVL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 80, 60));

        fondo_Imagen.setBackground(new java.awt.Color(84, 105, 106));

        javax.swing.GroupLayout fondo_ImagenLayout = new javax.swing.GroupLayout(fondo_Imagen);
        fondo_Imagen.setLayout(fondo_ImagenLayout);
        fondo_ImagenLayout.setHorizontalGroup(
            fondo_ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        fondo_ImagenLayout.setVerticalGroup(
            fondo_ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(fondo_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 100, 30));
        bg.add(bgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));
        bg.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 240, 20));

        lblIniciarSesion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Iniciar sesion");
        bg.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 240, -1));

        lblNombreUsu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNombreUsu.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreUsu.setText("Correo electronico:");
        bg.add(lblNombreUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 240, 20));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtCorreo.setText("Ingrese su correo electronico");
        txtCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCorreo.setCaretColor(new java.awt.Color(204, 204, 204));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        bg.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 240, 30));

        lblContraseña.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(0, 0, 0));
        lblContraseña.setText("Contraseña:");
        bg.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 240, 20));

        txtpass.setBackground(new java.awt.Color(255, 255, 255));
        txtpass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtpass.setForeground(new java.awt.Color(204, 204, 204));
        txtpass.setText("Contraseña");
        txtpass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpassMousePressed(evt);
            }
        });
        bg.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 240, 30));

        btnNoTengoCuanta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNoTengoCuanta.setForeground(new java.awt.Color(204, 204, 204));
        btnNoTengoCuanta.setText("¿No tienes cuenta?");
        btnNoTengoCuanta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoTengoCuanta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoTengoCuantaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoTengoCuantaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNoTengoCuantaMousePressed(evt);
            }
        });
        bg.add(btnNoTengoCuanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bibloteca/imagenes/loginImage.jpeg"))); // NOI18N
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 300, -1));

        btnCancelar.setBackground(new java.awt.Color(156, 207, 226));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        bg.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 110, 40));

        bntIngresar.setBackground(new java.awt.Color(41, 128, 185));
        bntIngresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bntIngresar.setForeground(new java.awt.Color(51, 51, 51));
        bntIngresar.setText("Ingresar");
        bntIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bntIngresarMousePressed(evt);
            }
        });
        bg.add(bntIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        if(txtCorreo.getText().equals("Ingrese su correo electronico")){
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
        if(String.valueOf(txtpass.getPassword()).isEmpty()){
            txtpass.setText("Contraseña");
            txtpass.setForeground(Color.GRAY);
        }

    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMousePressed
        if(String.valueOf(txtpass.getPassword()).equals("Contraseña")){
            txtpass.setText("");
            txtpass.setForeground(Color.black);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo electronico");
            txtCorreo.setForeground(Color.gray);
        }

    }//GEN-LAST:event_txtpassMousePressed

    private void btnNoTengoCuantaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoTengoCuantaMouseEntered
        btnNoTengoCuanta.setForeground(Color.BLUE);
    }//GEN-LAST:event_btnNoTengoCuantaMouseEntered

    private void btnNoTengoCuantaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoTengoCuantaMouseExited
        btnNoTengoCuanta.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnNoTengoCuantaMouseExited

    private void btnNoTengoCuantaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoTengoCuantaMousePressed
        Registro registro = new Registro();
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        Usuario usuario = new Usuario();
        
        ControlUsuario control = new ControlUsuario(registro, usuarioDAO, usuario);
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNoTengoCuantaMousePressed

    private void bntIngresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntIngresarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntIngresarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgLogin;
    public javax.swing.JButton bntIngresar;
    public javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnNoTengoCuanta;
    private javax.swing.JPanel fondo_Imagen;
    private javax.swing.JLabel iconoVL;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblNombreUsu;
    private javax.swing.JSeparator separador;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
