/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bibloteca.vista;

import com.bibloteca.controlador.ControlUsuarioInicio;
import com.bibloteca.controlador.UsuarioDAO;
import java.awt.Color;

/**
 *
 * @author r3sn0
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPassConf = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtApodo = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblIniciarSesion = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        fondo_Imagen = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bibloteca/imagenes/logo_main (3).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 120));

        jPanel4.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre completo:");

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Ingrese su nombre completo");
        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombre.setMaximumSize(new java.awt.Dimension(65, 20));
        txtNombre.setMinimumSize(new java.awt.Dimension(65, 20));
        txtNombre.setPreferredSize(new java.awt.Dimension(65, 20));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apodo:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contraseña:");

        txtPassConf.setBackground(new java.awt.Color(255, 255, 255));
        txtPassConf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPassConf.setForeground(new java.awt.Color(153, 153, 153));
        txtPassConf.setText("Ingrese su contrasena");
        txtPassConf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPassConf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPassConfMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassConfMousePressed(evt);
            }
        });
        txtPassConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassConfActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Confirmar contraseña:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Correo electronico:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Número telefonico:");

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPass.setForeground(new java.awt.Color(153, 153, 153));
        txtPass.setText("Ingrese su contrasena");
        txtPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPassMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassMousePressed(evt);
            }
        });

        txtApodo.setBackground(new java.awt.Color(255, 255, 255));
        txtApodo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtApodo.setForeground(new java.awt.Color(153, 153, 153));
        txtApodo.setText("Ingrese su apodo");
        txtApodo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtApodo.setMaximumSize(new java.awt.Dimension(65, 20));
        txtApodo.setMinimumSize(new java.awt.Dimension(65, 20));
        txtApodo.setPreferredSize(new java.awt.Dimension(65, 20));
        txtApodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtApodoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApodoMousePressed(evt);
            }
        });

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setText("Ingrese su correo electronico");
        txtCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCorreo.setMaximumSize(new java.awt.Dimension(65, 20));
        txtCorreo.setMinimumSize(new java.awt.Dimension(65, 20));
        txtCorreo.setPreferredSize(new java.awt.Dimension(65, 20));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefono.setText("Ingrese su numero telefonico");
        txtTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTelefono.setMaximumSize(new java.awt.Dimension(65, 20));
        txtTelefono.setMinimumSize(new java.awt.Dimension(65, 20));
        txtTelefono.setPreferredSize(new java.awt.Dimension(65, 20));
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassConf)
                            .addComponent(txtPass)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassConf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 450, 200));

        lblIniciarSesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(153, 153, 153));
        lblIniciarSesion.setText("Iniciar sesion");
        lblIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMousePressed(evt);
            }
        });
        jPanel1.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, 24));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("¿Ya tienes cuenta?");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 24));

        jPanel5.setOpaque(false);

        btnCancelar.setBackground(new java.awt.Color(156, 207, 226));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");

        btnRegistrar.setBackground(new java.awt.Color(41, 128, 185));
        btnRegistrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("Registar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistrarMousePressed(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnCancelar)
                .addGap(70, 70, 70)
                .addComponent(btnRegistrar)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 450, 80));

        fondo_Imagen.setBackground(new java.awt.Color(70, 88, 92));

        javax.swing.GroupLayout fondo_ImagenLayout = new javax.swing.GroupLayout(fondo_Imagen);
        fondo_Imagen.setLayout(fondo_ImagenLayout);
        fondo_ImagenLayout.setHorizontalGroup(
            fondo_ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        fondo_ImagenLayout.setVerticalGroup(
            fondo_ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(fondo_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 100, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bibloteca/imagenes/checkin_Image.jpeg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        if(txtNombre.getText().equals("Ingrese su nombre completo")){
            txtNombre.setText("");
            txtNombre.setForeground(Color.BLACK);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese un correo electronico");
            txtCorreo.setForeground(Color.gray);
        }
        if(txtApodo.getText().isEmpty()){
            txtApodo.setText("Ingrese su apodo");
            txtApodo.setForeground(Color.gray);
        }
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Ingrese su numero telefonico");
            txtTelefono.setForeground(Color.gray);
        }
        if(String.valueOf(txtPass.getPassword()).isEmpty()){
            txtPass.setText("Ingrese su contrasena");
            txtPass.setForeground(Color.gray); 
        }
        if(String.valueOf(txtPassConf.getPassword()).isEmpty()){
            txtPassConf.setText("Ingrese su contrasena");
            txtPassConf.setForeground(Color.gray); 
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtPassConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassConfActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        if(txtCorreo.getText().equals("Ingrese su correo electronico")){
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.BLACK);
        }
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Ingrese su nombre completo");
            txtNombre.setForeground(Color.gray);
        }
        if(txtApodo.getText().isEmpty()){
            txtApodo.setText("Ingrese su apodo");
            txtApodo.setForeground(Color.gray);
        }
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Ingrese su numero telefonico");
            txtTelefono.setForeground(Color.gray);
        }
        if(String.valueOf(txtPass.getPassword()).isEmpty()){
            txtPassConf.setText("Ingrese su contrasena");
            txtPassConf.setForeground(Color.gray); 
        }
        if(String.valueOf(txtPassConf.getPassword()).isEmpty()){
            txtPass.setText("Ingrese su contrasena");
            txtPass.setForeground(Color.gray); 
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtApodoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApodoMouseEntered
        
    }//GEN-LAST:event_txtApodoMouseEntered

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        if(txtTelefono.getText().equals("Ingrese su numero telefonico")){
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.BLACK);
        }
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Ingrese su nombre completo");
            txtNombre.setForeground(Color.gray);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo electronico");
            txtCorreo.setForeground(Color.gray);
        }
        if(txtApodo.getText().isEmpty()){
            txtApodo.setText("Ingrese su apodo");
            txtApodo.setForeground(Color.gray);
        }
        if(String.valueOf(txtPass.getPassword()).isEmpty()){
            txtPass.setText("Ingrese su contrasena");
            txtPass.setForeground(Color.gray); 
        }
        if(String.valueOf(txtPassConf.getPassword()).isEmpty()){
            txtPassConf.setText("Ingrese su contrasena");
            txtPassConf.setForeground(Color.gray); 
        }
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseEntered
        
    }//GEN-LAST:event_txtPassMouseEntered

    private void txtPassConfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassConfMouseEntered
        
    }//GEN-LAST:event_txtPassConfMouseEntered

    private void txtApodoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApodoMousePressed
        if(txtApodo.getText().equals("Ingrese su apodo")){
            txtApodo.setText("");
            txtApodo.setForeground(Color.BLACK);
        }
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Ingrese su nombre completo");
            txtNombre.setForeground(Color.gray);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo electronico");
            txtCorreo.setForeground(Color.gray);
        }
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Ingrese su numero telefonico");
            txtTelefono.setForeground(Color.gray);
        }
        if(String.valueOf(txtPass.getPassword()).isEmpty()){
            txtPass.setText("Ingrese su contrasena");
            txtPass.setForeground(Color.gray); 
        }
        if(String.valueOf(txtPassConf.getPassword()).isEmpty()){
            txtPassConf.setText("Ingrese su contrasena");
            txtPassConf.setForeground(Color.gray); 
        }
    }//GEN-LAST:event_txtApodoMousePressed

    private void txtPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMousePressed
        if(String.valueOf(txtPass.getPassword()).equals("Ingrese su contrasena")){
            txtPass.setText("");
            txtPass.setForeground(Color.BLACK);
        }
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Ingrese su nombre completo");
            txtNombre.setForeground(Color.gray);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo electronico");
            txtCorreo.setForeground(Color.gray);
        }
        if(txtApodo.getText().isEmpty()){
            txtApodo.setText("Ingrese su apodo");
            txtApodo.setForeground(Color.gray);
        }
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Ingrese su numero telefonico");
            txtTelefono.setForeground(Color.gray); 
        }
        if(String.valueOf(txtPassConf.getPassword()).isEmpty()){
            txtPassConf.setText("Ingrese su contrasena");
            txtPassConf.setForeground(Color.gray); 
        }
    }//GEN-LAST:event_txtPassMousePressed

    private void txtPassConfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassConfMousePressed
        if(String.valueOf(txtPassConf.getPassword()).equals("Ingrese su contrasena")){
            txtPassConf.setText("");
            txtPassConf.setForeground(Color.BLACK);
        }
        if(txtNombre.getText().isEmpty()){
            txtNombre.setText("Ingrese su nombre completo");
            txtNombre.setForeground(Color.gray);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo electronico");
            txtCorreo.setForeground(Color.gray);
        }
        if(txtApodo.getText().isEmpty()){
            txtApodo.setText("Ingrese su apodo");
            txtApodo.setForeground(Color.gray);
        }
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Ingrese su numero telefonico");
            txtTelefono.setForeground(Color.gray); 
        }
        if(String.valueOf(txtPass.getPassword()).isEmpty()){
            txtPass.setText("Ingrese su contrasena");
            txtPass.setForeground(Color.gray); 
        }
    }//GEN-LAST:event_txtPassConfMousePressed

    private void lblIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseEntered
        lblIniciarSesion.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblIniciarSesionMouseEntered

    private void lblIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseExited
        lblIniciarSesion.setForeground(Color.gray);
    }//GEN-LAST:event_lblIniciarSesionMouseExited

    private void lblIniciarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMousePressed
        InicioSesion inicio = new InicioSesion();
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        
        ControlUsuarioInicio control = new ControlUsuarioInicio(inicio, usuarioDAO);
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblIniciarSesionMousePressed

    private void btnRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMousePressed
    
    }//GEN-LAST:event_btnRegistrarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel fondo_Imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIniciarSesion;
    public javax.swing.JTextField txtApodo;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JPasswordField txtPass;
    public javax.swing.JPasswordField txtPassConf;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
